### ISSUE TITLE
Подготовка к тестированию бекенда

### ISSUE THREAD

**Issue by orthlus** [kino-online/frontend#1]
нужно привести текущий стенд к следующему виду
- уменьшить размер плеера чтобы вписывался в full hd экран
- над плеером добавить инпут для ссылки на m3u8 файл плейлиста
  - текущий файл - https://github.com/iLampa/frontend/blob/master/src/app/view/view.component.ts#L20
- кнопку для инпута для перезагрузки плеера с новым файлом
- по умолчанию остается текущий файл

**Comment by orthlus** [comment]
выложил в #2 внешний файл

**Comment by ksenkso** [comment]
Плеер теперь подстраивается под ширину экрана.
Над плеером добавлен инпут для урла - работает только с `.m3u8`-файлами. Кнопка там же рядом. После переключения источника автоплея нет.
По дефолту остался текущий файл.
